### ISSUE TITLE
Command with negative search chrashes server

### ISSUE THREAD

**Issue by mattboban** [RedisLabsModules/RediSearch#156]
redis_version:4.0.1 / search 0.20.0

runinng command formated as followong, chrases redis serve:

`ft.search menu-api_dev:restaurant-index "(-@associations:NULL|-@reviews:NULL)" verbatim`

the only relevant notation in the server logs is:

> [ 2862.905082] redis-server[1222]: segfault at 856ff0 ip 00007effae4568b6 sp 00007ffdc633e628 error 4 in libc-2.23.so[7effae2fc000+1c0000]

**Comment by dvirsky** [comment]
Actually the entire stack trace would be useful :)

**Comment by dvirsky** [comment]
Also, if you can provide a script that recreates it or a database dump that can be used to recreate it would be wonderful, I can't recreate it locally

**Comment by dvirsky** [comment]
Okay, I've managed to recreate and fix it (I hope) in cffe0fddc3699. Please pull and verify. Thanks, great find!

**Comment by mattboban** [comment]
@dvirsky you are faster than my sir, very cool. 
I can confirm that this appears to have solved it as I can't recreate the crash with the command:

`ft.search menu-api_dev:restaurant-index '(@city:Nashville @state:3967 @country:225 @associations:NULL -@contacts:NULL)' filter status 1 1 limit 0 25 nocontent` 

I'll continue testing thru the day with 1m+ datasets, and update you with any additional relevant findings.

note that the *make test* notes a few errors:
```
make -C ./src test
make[1]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src'
make -C trie
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/trie'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/trie'
make -C dep/triemap
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/dep/triemap'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/dep/triemap'
make -C rmutil
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/rmutil'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/rmutil'
make -C dep/libnu
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/dep/libnu'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/dep/libnu'
make -C dep/snowball libstemmer.o
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/dep/snowball'
make[2]: 'libstemmer.o' is up to date.
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/dep/snowball'
# Just to make sure old versions of the modules are deleted
rm -f module.so
ld -o redisearch.so  /home/ubuntu/redis_modules/RediSearch/src/inverted_index.o  /home/ubuntu/redis_modules/RediSearch/src/id_filter.o  /home/ubuntu/redis_modules/RediSearch/src/concurrent_ctx.o  /home/ubuntu/redis_modules/RediSearch/src/spec.o  /home/ubuntu/redis_modules/RediSearch/src/buffer.o  /home/ubuntu/redis_modules/RediSearch/src/varint.o  /home/ubuntu/redis_modules/RediSearch/src/id_list.o  /home/ubuntu/redis_modules/RediSearch/src/qint.o  /home/ubuntu/redis_modules/RediSearch/src/sortable.o  /home/ubuntu/redis_modules/RediSearch/src/geo_index.o  /home/ubuntu/redis_modules/RediSearch/src/indexer.o  /home/ubuntu/redis_modules/RediSearch/src/tokenize.o  /home/ubuntu/redis_modules/RediSearch/src/extension.o  /home/ubuntu/redis_modules/RediSearch/src/index_result.o  /home/ubuntu/redis_modules/RediSearch/src/index.o  /home/ubuntu/redis_modules/RediSearch/src/document.o  /home/ubuntu/redis_modules/RediSearch/src/config.o  /home/ubuntu/redis_modules/RediSearch/src/stemmer.o  /home/ubuntu/redis_modules/RediSearch/src/stopwords.o  /home/ubuntu/redis_modules/RediSearch/src/doc_table.o  /home/ubuntu/redis_modules/RediSearch/src/gc.o  /home/ubuntu/redis_modules/RediSearch/src/document_basic.o  /home/ubuntu/redis_modules/RediSearch/src/redis_index.o  /home/ubuntu/redis_modules/RediSearch/src/search_request.o  /home/ubuntu/redis_modules/RediSearch/src/numeric_filter.o  /home/ubuntu/redis_modules/RediSearch/src/module.o  /home/ubuntu/redis_modules/RediSearch/src/offset_vector.o  /home/ubuntu/redis_modules/RediSearch/src/forward_index.o  /home/ubuntu/redis_modules/RediSearch/src/numeric_index.o  /home/ubuntu/redis_modules/RediSearch/src/query.o  /home/ubuntu/redis_modules/RediSearch/src/query_parser/lexer.o  /home/ubuntu/redis_modules/RediSearch/src/query_parser/parser.o  /home/ubuntu/redis_modules/RediSearch/src/ext/default.o  /home/ubuntu/redis_modules/RediSearch/src/util/heap.o  /home/ubuntu/redis_modules/RediSearch/src/util/fnv.o  /home/ubuntu/redis_modules/RediSearch/src/util/mempool.o  /home/ubuntu/redis_modules/RediSearch/src/util/block_alloc.o  /home/ubuntu/redis_modules/RediSearch/src/util/khtable.o  /home/ubuntu/redis_modules/RediSearch/src/util/logging.o  /home/ubuntu/redis_modules/RediSearch/src/trie/levenshtein.o  /home/ubuntu/redis_modules/RediSearch/src/trie/trie.o  /home/ubuntu/redis_modules/RediSearch/src/trie/sparse_vector.o  /home/ubuntu/redis_modules/RediSearch/src/trie/trie_type.o  /home/ubuntu/redis_modules/RediSearch/src/trie/rune_util.o  /home/ubuntu/redis_modules/RediSearch/src/dep/thpool/thpool.o trie/libtrie.a dep/triemap/libtriemap.a rmutil/librmutil.a dep/libnu/libnu.a dep/snowball/libstemmer.o -shared -Bsymbolic -Bsymbolic-functions -ldl -lpthread -lc -lm
ar rcs libredisearch.a  /home/ubuntu/redis_modules/RediSearch/src/inverted_index.o  /home/ubuntu/redis_modules/RediSearch/src/id_filter.o  /home/ubuntu/redis_modules/RediSearch/src/concurrent_ctx.o  /home/ubuntu/redis_modules/RediSearch/src/spec.o  /home/ubuntu/redis_modules/RediSearch/src/buffer.o  /home/ubuntu/redis_modules/RediSearch/src/varint.o  /home/ubuntu/redis_modules/RediSearch/src/id_list.o  /home/ubuntu/redis_modules/RediSearch/src/qint.o  /home/ubuntu/redis_modules/RediSearch/src/sortable.o  /home/ubuntu/redis_modules/RediSearch/src/geo_index.o  /home/ubuntu/redis_modules/RediSearch/src/indexer.o  /home/ubuntu/redis_modules/RediSearch/src/tokenize.o  /home/ubuntu/redis_modules/RediSearch/src/extension.o  /home/ubuntu/redis_modules/RediSearch/src/index_result.o  /home/ubuntu/redis_modules/RediSearch/src/index.o  /home/ubuntu/redis_modules/RediSearch/src/document.o  /home/ubuntu/redis_modules/RediSearch/src/config.o  /home/ubuntu/redis_modules/RediSearch/src/stemmer.o  /home/ubuntu/redis_modules/RediSearch/src/stopwords.o  /home/ubuntu/redis_modules/RediSearch/src/doc_table.o  /home/ubuntu/redis_modules/RediSearch/src/gc.o  /home/ubuntu/redis_modules/RediSearch/src/document_basic.o  /home/ubuntu/redis_modules/RediSearch/src/redis_index.o  /home/ubuntu/redis_modules/RediSearch/src/search_request.o  /home/ubuntu/redis_modules/RediSearch/src/numeric_filter.o  /home/ubuntu/redis_modules/RediSearch/src/module.o  /home/ubuntu/redis_modules/RediSearch/src/offset_vector.o  /home/ubuntu/redis_modules/RediSearch/src/forward_index.o  /home/ubuntu/redis_modules/RediSearch/src/numeric_index.o  /home/ubuntu/redis_modules/RediSearch/src/query.o  /home/ubuntu/redis_modules/RediSearch/src/query_parser/lexer.o  /home/ubuntu/redis_modules/RediSearch/src/query_parser/parser.o  /home/ubuntu/redis_modules/RediSearch/src/ext/default.o  /home/ubuntu/redis_modules/RediSearch/src/util/heap.o  /home/ubuntu/redis_modules/RediSearch/src/util/fnv.o  /home/ubuntu/redis_modules/RediSearch/src/util/mempool.o  /home/ubuntu/redis_modules/RediSearch/src/util/block_alloc.o  /home/ubuntu/redis_modules/RediSearch/src/util/khtable.o  /home/ubuntu/redis_modules/RediSearch/src/util/logging.o  /home/ubuntu/redis_modules/RediSearch/src/trie/levenshtein.o  /home/ubuntu/redis_modules/RediSearch/src/trie/trie.o  /home/ubuntu/redis_modules/RediSearch/src/trie/sparse_vector.o  /home/ubuntu/redis_modules/RediSearch/src/trie/trie_type.o  /home/ubuntu/redis_modules/RediSearch/src/trie/rune_util.o  /home/ubuntu/redis_modules/RediSearch/src/dep/thpool/thpool.o
make -C tests build
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/tests'
test_trie.c: In function ‘testTrie’:
test_trie.c:184:48: warning: passing argument 3 of ‘TrieNode_RandomWalk’ from incompatible pointer type [-Wincompatible-pointer-types]
   TrieNode *rn = TrieNode_RandomWalk(root, 10, &str, &l);
                                                ^
In file included from test_trie.c:1:0:
../trie/trie.h:195:11: note: expected ‘rune ** {aka short unsigned int **}’ but argument is of type ‘char **’
 TrieNode *TrieNode_RandomWalk(TrieNode *n, int minSteps, rune **str, t_len *len);
           ^
make[3]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/tests/ext-example'
make[3]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/tests/ext-example'
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/tests'
# low level redis-independant tests
make -C ./tests test
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/tests'
Starting Test './test_index'...
  Testing testAbort		[PASS]
  Testing testNumericInverted		written 218 bytes
1 1.000000
2 2.000000
3 3.000000
4 4.000000
5 5.000000
6 6.000000
7 7.000000
8 8.000000
9 9.000000
10 10.000000
11 11.000000
12 12.000000
13 13.000000
14 14.000000
15 15.000000
16 16.000000
17 17.000000
18 18.000000
19 19.000000
20 20.000000
21 21.000000
22 22.000000
23 23.000000
24 24.000000
25 25.000000
26 26.000000
27 27.000000
28 28.000000
29 29.000000
30 30.000000
31 31.000000
32 32.000000
33 33.000000
34 34.000000
35 35.000000
36 36.000000
37 37.000000
38 38.000000
39 39.000000
40 40.000000
41 41.000000
42 42.000000
43 43.000000
44 44.000000
45 45.000000
46 46.000000
47 47.000000
48 48.000000
49 49.000000
50 50.000000
51 51.000000
52 52.000000
53 53.000000
54 54.000000
55 55.000000
56 56.000000
57 57.000000
58 58.000000
59 59.000000
60 60.000000
61 61.000000
62 62.000000
63 63.000000
64 64.000000
65 65.000000
66 66.000000
67 67.000000
68 68.000000
69 69.000000
70 70.000000
71 71.000000
72 72.000000
73 73.000000
74 74.000000
75 75.000000
[PASS]
  Testing testNumericVaried		Checking i=0. Expected=0.000000
Checking i=1. Expected=0.130000
Checking i=2. Expected=0.001000
Checking i=3. Expected=-0.100000
Checking i=4. Expected=1.000000
Checking i=5. Expected=5.000000
Checking i=6. Expected=4.323000
Checking i=7. Expected=65535.000000
Checking i=8. Expected=65535.530000
Checking i=9. Expected=32768.432000
Checking i=10. Expected=4294967296.000000
Checking i=11. Expected=18446744069414584320.000000
Checking i=12. Expected=1099511627776.000000
[PASS]
  Testing testNumericEncoding		[PASS]
  Testing testVarint		[PASS]
  Testing testDistance		[PASS]
  Testing testIndexReadWrite		[PASS]
  Testing testReadIterator		[PASS]
  Testing testIntersection		[PASS]
  Testing testNot		[PASS]
  Testing testUnion		[PASS]
  Testing testBuffer		[PASS]
  Testing testTokenize		[PASS]
  Testing testIndexSpec		[PASS]
  Testing testIndexFlags		[PASS]
  Testing testDocTable		[PASS]
  Testing testSortable		[PASS]

Total: 17 tests and 164657 assertions OK

--------------------

Starting Test './test_stemmer'...
  Testing testStemmer		stem: arbitrari
[PASS]
  Testing testTokenize		[PASS]

Total: 2 tests and 6 assertions OK

--------------------

Starting Test './test_trie'...
  Testing testRuneUtil		[PASS]
  Testing testDFAFilter		loaded 4861 entries
[PASS]
  Testing testTrie		 found node: h
[PASS]
  Testing testPayload		[PASS]
  Testing testUnicode		[PASS]

Total: 5 tests and 7740 assertions OK

--------------------

Starting Test './test_range'...
  Testing testNumericRangeTree		[PASS]
  Testing testRangeIterator		[PASS]
Execution time for 1000 iterations of { Vector *v = NumericRangeTree_Find(t, 1000, 20000); Vector_Free(v); }: 0.000309 msec/iteration

Total: 2 tests and 12787452 assertions OK

--------------------

Starting Test './test_extensions'...
  Testing testExtenionRegistration		[PASS]
  Testing testQueryExpander		[PASS]
  Testing testDynamicLoading		[PASS]

Total: 3 tests and 35 assertions OK

--------------------

Starting Test './test_query'...
  Testing testQueryParser		hello
INTERSECT {
  hello
  PREFIX{wor*}
}
INTERSECT {
  hello
  world
}
INTERSECT {
  hello
  world
}
EXACT {
  hello
  world
}
hello
INTERSECT {
  EXACT {
    hello
    world
  }
  EXACT {
    foo
    bar
  }
}
UNION {
  EXACT {
    hello
    world
  }
  EXACT {
    foo
    bar
  }
}
INTERSECT {
  EXACT {
    hello
    world
  }
  EXACT {
    foo
    bar
  }
}
INTERSECT {
  hello
  EXACT {
    foo
    bar
  }
  world
}
INTERSECT {
  UNION {
    hello
    hallo
    yellow
  }
  world
}
INTERSECT {
  UNION {
    hello
    world
    foo
  }
  bar
  baz
  123
}
INTERSECT {
  UNION {
    hello
    world
    foo
  }
  INTERSECT {
    bar
    baz
  }
}
@title|body:INTERSECT {
  @title:INTERSECT {
    barack
    obama
  }
  @body:UNION {
    @body:us
    @body:president
  }
}
@body:INTERSECT {
  @NULL:INTERSECT {
    @NULL:barack
    @NULL:obama
  }
  @body:us
}
@title|body:INTERSECT {
  @title:barack
  @body:obama
}
@title|body:INTERSECT {
  @NULL:barack
  @title|body:obama
}
INTERSECT {
  hello
  world
  good
  bye
  foo
  bar
}
@NULL:EXACT {
  wells
  fargo
  bank
  national
  association
}
INTERSECT {
  foo
  NOT{
    bar
  }
  NOT{
    INTERSECT {
      bar
      baz
    }
  }
}
UNION {
  INTERSECT {
    hello
    world
  }
  INTERSECT {
    goodbye
    moon
  }
}
Error parsing query '@title:': Syntax error at offset 6 near 'title'
Error parsing query '@body:@title:': Syntax error at offset 12 near 'title'
Error parsing query '@body|title:@title:': Syntax error at offset 18 near 'title'
Error parsing query '@body|title': Syntax error at offset 6 near 'title'
INTERSECT {
  hello
  OPTIONAL{
    world
  }
  OPTIONAL{
    war
  }
}
INTERSECT {
  hello
  OPTIONAL{
    INTERSECT {
      world
      war
    }
  }
}
INTERSECT {
  <WILDCARD>}
  NOT{
    foo
  }
}
INTERSECT {
  <WILDCARD>}
  @title:NOT{
    foo
  }
}
INTERSECT {
  <WILDCARD>}
  NOT{
    @title:foo
  }
}
NUMERIC {100.000000 <= @number <= 200.000000}
NUMERIC {100.000000 <= @number <= -200.000000}
NUMERIC {100.000000 < @number < 200.000000}
NUMERIC {100.000000 <= @number <= inf}
NUMERIC {100.000000 <= @number <= -inf}
NUMERIC {-inf <= @number <= inf}
UNION {
  NUMERIC {-inf <= @number <= inf}
  NUMERIC {100.000000 <= @number <= 200.000000}
}
Error parsing query '@number:[100 foo]': Syntax error at offset 13 near 'foo'
Error parsing query '(foo': Syntax error at offset 1 near 'foo'
Error parsing query '"foo': Syntax error at offset 1 near 'foo'
test_query.c:36 Assertion 'n != ((void *)0)' Failed
Error parsing query '()': Syntax error at offset 1 near ''
INTERSECT {
  שלום
  עולם
}
INTERSECT {
  UNION {
    hello
    world
  }
  EXACT {
    another
    world
  }
  INTERSECT {
    foo
    bar
  }
  NOT{
    INTERSECT {
      baz
      PREFIX{boo*}
    }
  }
}
[PASS]
  Testing testPureNegative		[PASS]
  Testing testFieldSpec		@title:INTERSECT {
  @title:hello
  @title:world
}
(@title:hello) (@body:world) ====> @title|body:INTERSECT {
  @title:hello
  @body:world
}
@title:(hello world) @body:(world apart) @adas_dfsd:fofofof ====> @title|body:INTERSECT {
  @title|body:INTERSECT {
    @title:INTERSECT {
      hello
      world
    }
    @body:INTERSECT {
      world
      apart
    }
  }
  @NULL:fofofof
}
[PASS]
Execution time for 50000 iterations of { Query_Parse(q, &err); }: 0.001749 msec/iteration

Total: 3 tests and 121 assertions OK

--------------------

Starting Test './test_stopwords'...
  Testing testStopwordList		[PASS]
  Testing testDefaultStopwords		[PASS]

Total: 2 tests and 50 assertions OK

--------------------

Starting Test './test_blkalloc'...
  Testing testBlockAlloc		[PASS]
  Testing testFreeFunc		[PASS]

Total: 2 tests and 20 assertions OK

--------------------

Starting Test './test_khtable'...
  Testing testKhTable		[PASS]

Total: 1 tests and 6 assertions OK

--------------------

make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/tests'
# high level python integration tests
make -C pytest test
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/pytest'
python -m unittest discover
make[2]: python: Command not found
Makefile:2: recipe for target 'test' failed
make[2]: *** [test] Error 127
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/pytest'
Makefile:97: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src'
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by dvirsky** [comment]
The tests fail because you don't have Python installed on the machine

```
Makefile:2: recipe for target 'test' failed
make[2]: *** [test] Error 127
```

**Comment by dvirsky** [comment]
Sorry wrong paste

```
python -m unittest discover
make[2]: python: Command not found
```

**Comment by mattboban** [comment]
That could be it :)    Just updated to the latest to latest:

`python -V
Python 2.7.12`
`python3 -V
Python 3.5.2`

and getting different failures:

```
Total: 3 tests and 121 assertions OK

--------------------

Starting Test './test_stopwords'...
  Testing testStopwordList		[PASS]
  Testing testDefaultStopwords		[PASS]

Total: 2 tests and 50 assertions OK

--------------------

Starting Test './test_blkalloc'...
  Testing testBlockAlloc		[PASS]
  Testing testFreeFunc		[PASS]

Total: 2 tests and 20 assertions OK

--------------------

Starting Test './test_khtable'...
  Testing testKhTable		[PASS]

Total: 1 tests and 6 assertions OK

--------------------

make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/tests'
# high level python integration tests
make -C pytest test
make[2]: Entering directory '/home/ubuntu/redis_modules/RediSearch/src/pytest'
python -m unittest discover
EEE
======================================================================
ERROR: test_fuzz (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_fuzz
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/redis_modules/RediSearch/src/pytest/test_fuzz.py", line 1, in <module>
    from rmtest import ModuleTestCase
ImportError: No module named rmtest


======================================================================
ERROR: test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/redis_modules/RediSearch/src/pytest/test.py", line 1, in <module>
    from rmtest import ModuleTestCase
ImportError: No module named rmtest


======================================================================
ERROR: test_ext (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ext
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/redis_modules/RediSearch/src/pytest/test_ext.py", line 1, in <module>
    from rmtest import ModuleTestCase
ImportError: No module named rmtest


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)
Makefile:2: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src/pytest'
Makefile:97: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/ubuntu/redis_modules/RediSearch/src'
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 2
```

Posebly still my box configuration?

**Comment by dvirsky** [comment]
Python 3. The tests are written in Python 2 :/
