### ISSUE TITLE
Redis 4.0.2 crashes when using RediSearch 0.21.2

### ISSUE THREAD

**Issue by id4coding** [RedisLabsModules/RediSearch#179]
I was trying to use Redisearch using redisearch-rb ruby gem on Redis 4.0.2. Redis crashes at add_docs method of the gem.

The stack trace of the ruby program (up to add_docs) is pasted below.

```
/usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:255:in `rescue in io': Connection lost (ECONNRESET) (Redis::ConnectionError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:248:in `io'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:259:in `read'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:191:in `block (2 levels) in call_pipelined'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:190:in `times'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:190:in `block in call_pipelined'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:229:in `block (2 levels) in process'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:366:in `ensure_connected'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:185:in `call_pipelined'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:155:in `block in call_pipeline'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:153:in `call_pipeline'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:2353:in `block in multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
        from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:2345:in `multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redisearch-rb-0.1.8/lib/redisearch.rb:122:in `block in multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:51:in `block in with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
        from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:50:in `with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redisearch-rb-0.1.8/lib/redisearch.rb:122:in `multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redisearch-rb-0.1.8/lib/redisearch.rb:90:in `add_docs'
```

The stack trace of Redis is pasted below.

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
18821:M 04 Oct 15:36:05.867 # ------------------------------------------------
18821:M 04 Oct 15:36:05.867 # !!! Software Failure. Press left mouse button to continue
18821:M 04 Oct 15:36:05.867 # Guru Meditation: Unknown btype in unblockClient(). #blocked.c:142
18821:M 04 Oct 15:36:05.867 # (forcing SIGSEGV in order to print the stack trace)
18821:M 04 Oct 15:36:05.867 # ------------------------------------------------
18821:M 04 Oct 15:36:05.867 # Redis 4.0.2 crashed by signal: 11
18821:M 04 Oct 15:36:05.867 # Crashed running the instuction at: 0x469147
18821:M 04 Oct 15:36:05.867 # Accessing address: 0xffffffffffffffff
18821:M 04 Oct 15:36:05.867 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/local/bin/redis-server 127.0.0.1:6379(_serverPanic+0x137)[0x469147]

Backtrace:
/usr/local/bin/redis-server 127.0.0.1:6379(logStackTrace+0x45)[0x46acb5]
/usr/local/bin/redis-server 127.0.0.1:6379(sigsegvHandler+0xb9)[0x46b479]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f9aa755d390]
/usr/local/bin/redis-server 127.0.0.1:6379(_serverPanic+0x137)[0x469147]
/usr/local/bin/redis-server 127.0.0.1:6379(unblockClient+0x9d)[0x489d9d]
/usr/local/bin/redis-server 127.0.0.1:6379(moduleHandleBlockedClients+0xb7)[0x495757]
/usr/local/bin/redis-server 127.0.0.1:6379(beforeSleep+0x57)[0x429107]
/usr/local/bin/redis-server 127.0.0.1:6379(aeMain+0x1e)[0x425cbe]
/usr/local/bin/redis-server 127.0.0.1:6379(main+0x4a6)[0x422896]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9aa71a2830]
/usr/local/bin/redis-server 127.0.0.1:6379(_start+0x29)[0x422b99]

------ INFO OUTPUT ------
# Server
redis_version:4.0.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:78e2272687649b75
redis_mode:standalone
os:Linux 4.4.0-45-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:5.4.0
process_id:18821
run_id:3a743c3e91e7f0ea4b8107efe59540ea9d1363c2
tcp_port:6379
uptime_in_seconds:293
uptime_in_days:0
hz:10
lru_clock:13939341
executable:/usr/local/bin/redis-server
config_file:/etc/redis/6379.conf

# Clients
connected_clients:3
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:7

# Memory
used_memory:1065200
used_memory_human:1.02M
used_memory_rss:4919296
used_memory_rss_human:4.69M
used_memory_peak:1065200
used_memory_peak_human:1.02M
used_memory_peak_perc:119.14%
used_memory_overhead:849834
used_memory_startup:765728
used_memory_dataset:215366
used_memory_dataset_perc:71.92%
total_system_memory:2097528832
total_system_memory_human:1.95G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:4.62
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:4
rdb_bgsave_in_progress:0
rdb_last_save_time:1507111272
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:3
total_commands_processed:16
instantaneous_ops_per_sec:1
total_net_input_bytes:1642
total_net_output_bytes:256
instantaneous_input_kbps:0.07
instantaneous_output_kbps:0.02
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:2932
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:2faea7e766216efb887bd10a869959c1506ae4ea
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.29
used_cpu_user:0.33
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_multi:calls=1,usec=1,usec_per_call=1.00
cmdstat_set:calls=1,usec=39,usec_per_call=39.00
cmdstat_exec:calls=9,usec=1242,usec_per_call=138.00
cmdstat_geoadd:calls=2,usec=41,usec_per_call=20.50
cmdstat_info:calls=1,usec=128,usec_per_call=128.00
cmdstat_get:calls=1,usec=14,usec_per_call=14.00
cmdstat_keys:calls=1,usec=39,usec_per_call=39.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=15,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=135 addr=127.0.0.1:60636 fd=7 name= age=279 idle=279 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=keys
id=2927 addr=127.0.0.1:60748 fd=8 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=set
id=2928 addr=127.0.0.1:60752 fd=9 name= age=0 idle=0 flags=u db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=10 oll=0 omem=0 events=r cmd=exec

------ REGISTERS ------
18821:M 04 Oct 15:36:05.868 # 
RAX:0000000000000000 RBX:000000000051c5d2
RCX:0000000000000000 RDX:0000000000000000
RDI:00007f9aa7546b20 RSI:0000000000000000
RBP:000000000000008e RSP:00007ffd143aca10
R8 :00007f9aa7e87780 R9 :0000000000000001
R10:0000000000000030 R11:0000000000000246
R12:00007ffd143ace58 R13:0000000000000002
R14:00007f9aa68166c3 R15:0000000000000000
RIP:0000000000469147 EFL:0000000000010206
CSGSFS:0000000000000033
18821:M 04 Oct 15:36:05.868 # (00007ffd143aca1f) -> 0000000000002210
18821:M 04 Oct 15:36:05.868 # (00007ffd143aca1e) -> 00007f9aa6e00180
18821:M 04 Oct 15:36:05.868 # (00007ffd143aca1d) -> 00000000004fe8b4
18821:M 04 Oct 15:36:05.868 # (00007ffd143aca1c) -> 0000000000000040
18821:M 04 Oct 15:36:05.868 # (00007ffd143aca1b) -> 00007f9aa6e00180
18821:M 04 Oct 15:36:05.868 # (00007ffd143aca1a) -> 00007f9aa680d460
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca19) -> 0000000000000028
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca18) -> 00007f9aa6e0002e
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca17) -> 2928746e65696c43
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca16) -> 6b636f6c626e7520
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca15) -> 6e69206570797462
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca14) -> 206e776f6e6b6e55
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca13) -> 00007ffd143acb40
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca12) -> 00007ffd143acc10
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca11) -> 0000003000000018
18821:M 04 Oct 15:36:05.869 # (00007ffd143aca10) -> 00007f9aa6e00188

------ FAST MEMORY TEST ------
18821:M 04 Oct 15:36:05.869 # Bio thread for job type #0 terminated
18821:M 04 Oct 15:36:05.869 # Bio thread for job type #1 terminated
18821:M 04 Oct 15:36:05.869 # Bio thread for job type #2 terminated
*** Preparing to test memory region 758000 (98304 bytes)
*** Preparing to test memory region 265b000 (135168 bytes)
*** Preparing to test memory region 7f9a90000000 (135168 bytes)
*** Preparing to test memory region 7f9a98000000 (135168 bytes)
*** Preparing to test memory region 7f9a9e600000 (2097152 bytes)
*** Preparing to test memory region 7f9a9ea00000 (10485760 bytes)
*** Preparing to test memory region 7f9a9f552000 (8388608 bytes)
*** Preparing to test memory region 7f9a9fd53000 (8388608 bytes)
*** Preparing to test memory region 7f9aa0554000 (8388608 bytes)
*** Preparing to test memory region 7f9aa0d55000 (8388608 bytes)
*** Preparing to test memory region 7f9aa1556000 (8388608 bytes)
*** Preparing to test memory region 7f9aa1d57000 (8388608 bytes)
*** Preparing to test memory region 7f9aa2558000 (8388608 bytes)
*** Preparing to test memory region 7f9aa2d59000 (8388608 bytes)
*** Preparing to test memory region 7f9aa355a000 (8388608 bytes)
*** Preparing to test memory region 7f9aa3d5b000 (8388608 bytes)
*** Preparing to test memory region 7f9aa455c000 (8388608 bytes)
*** Preparing to test memory region 7f9aa4ffe000 (8388608 bytes)
*** Preparing to test memory region 7f9aa57ff000 (8388608 bytes)
*** Preparing to test memory region 7f9aa6000000 (8388608 bytes)
*** Preparing to test memory region 7f9aa6800000 (2097152 bytes)
*** Preparing to test memory region 7f9aa6e00000 (2097152 bytes)
*** Preparing to test memory region 7f9aa7548000 (16384 bytes)
*** Preparing to test memory region 7f9aa7765000 (16384 bytes)
*** Preparing to test memory region 7f9aa7e87000 (16384 bytes)
*** Preparing to test memory region 7f9aa7e99000 (8192 bytes)
*** Preparing to test memory region 7f9aa7e9d000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: _serverPanic (base: 0x469010)
Module: /usr/local/bin/redis-server 127.0.0.1:6379 (base 0x400000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x469010 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
18821:M 04 Oct 15:36:06.591 # dump of function (hexdump of 439 bytes):
555389f54889fb4881ece801000084c048898c24480100004c898424500100004c898c245801000074400f298424600100000f298c24700100000f299424800100000f299c24900100000f29a424a00100000f29ac24b00100000f29b424c00100000f29bc24d001000064488b042528000000488984242801000031c0488d8424000200004c8d4c2408488d7c24204989d0b900010000ba010000004889442410488d842430010000be00010000c744240818000000c744240c300000004889442418e8988dfbff8b05fe122f0085c07505e809f8ffff31c0be683d5100bf03000000e8e804fcff31c0bea03d5100bf03000000e8d704fcff488d5424204189e84889d931c0be924e5100bf03000000e8bb04fcff31c0bee03d5100bf03000000e8aa04fcff31c0be683d5100bf03000000e89904fcffc60425ffffffff78488b842428010000644833042528000000750a4881c4e80100005b5dc3e8ff86fbff0f1f440000662e0f1f840000000000415741564155415455534881ec9801000048c7070000000048c7470800000000c74710000000008b055b0d2f0064488b0c252800000048898c248801000031c948897c241085c0

=== REDIS BUG REPORT END. Make sure to include from START to END. ===
```

**Comment by mnunberg** [comment]
Were you running this in a pipeline? Can you give us a quick snippet of code to reproduce?

**Comment by id4coding** [comment]
I tried with Redis latest unstable version. Now, Redis doesn't crash. But, the ruby program produces this stack trace with the following error message:

```
/usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:123:in `value': ERR Blocking module command called from transaction (Redis::CommandError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:115:in `_set'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:57:in `block in finish'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:56:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:56:in `each_with_index'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:56:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:56:in `map'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:56:in `finish'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/pipeline.rb:80:in `finish'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:155:in `block in call_pipeline'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:153:in `call_pipeline'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:2353:in `block in multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
        from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:2345:in `multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redisearch-rb-0.1.8/lib/redisearch.rb:122:in `block in multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:51:in `block in with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
        from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:50:in `with_reconnect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redisearch-rb-0.1.8/lib/redisearch.rb:122:in `multi'
        from /usr/local/lib/ruby/gems/2.3.0/gems/redisearch-rb-0.1.8/lib/redisearch.rb:90:in `add_docs'
```


I'll try to come up with a code snippet that I can share.

**Comment by dvirsky** [comment]
that is expected behavior, not a bug. do not use the search commands within a multi transaction. thanks.

**Comment by dvirsky** [comment]
if that is the default behavior of redisearch rb, please open an issue in the client repo though.

**Comment by autocorrectoff** [comment]
it's okay to use ft.adds in multi transaction, correct @dvirsky ?
