### ISSUE TITLE
RediSearch crashes with HIGHLIGHT and higher LIMIT in 1.4.0

### ISSUE THREAD

**Issue by krisbarrett** [RedisLabsModules/RediSearch#522]
Using the 1.4.0 release, RediSearch consistently crashes with HIGHLIGHT and higher LIMIT.  This command crashes:
```
"FT.SEARCH" "v1-variations" "@section_name: Report Review" "LIMIT" "0" "100" "WITHSCORES" "HIGHLIGHT" "TAGS" "<b>" "</b>"
```

This command does not:
```
"FT.SEARCH" "v1-variations" "@section_name: Report Review" "LIMIT" "0" "50" "WITHSCORES" "HIGHLIGHT" "TAGS" "<b>" "</b>"
```

Backtrace:
```
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:120
#1  0x00007f6623761808 in FragmentList_HighlightWholeDocS () from /usr/lib/redis/modules/redisearch.so
#2  0x00007f6623772c29 in summarizeField () from /usr/lib/redis/modules/redisearch.so
#3  0x00007f66237730eb in processField () from /usr/lib/redis/modules/redisearch.so
#4  0x00007f6623773496 in hlp_Next () from /usr/lib/redis/modules/redisearch.so
#5  0x00007f6623759dfd in ResultProcessor_Next () from /usr/lib/redis/modules/redisearch.so
#6  0x00007f662375a3cd in Query_SerializeResults () from /usr/lib/redis/modules/redisearch.so
#7  0x00007f662375ad2d in QueryPlan_Run () from /usr/lib/redis/modules/redisearch.so
#8  0x00007f662376a355 in _SearchCommand () from /usr/lib/redis/modules/redisearch.so
#9  0x00007f662374d234 in threadHandleCommand () from /usr/lib/redis/modules/redisearch.so
#10 0x00007f66238040c0 in thread_do () from /usr/lib/redis/modules/redisearch.so
#11 0x00007f662602a6ba in start_thread (arg=0x7f662295d700) at pthread_create.c:333
```

**Comment by krisbarrett** [comment]
I realized that this has nothing to do with higher limits, but rather one of the documents had an empty text field.  I was able to create a work-around by making sure that fields are never empty by using some placeholder text.  However, an empty text field should not cause redisearch to crash with highlights.

**Comment by MeirShpilraien** [comment]
@krisbarrett can you send the reproduction steps, I was not able to reproduce locally on my machine.

**Comment by mnunberg** [comment]
I haven't checked, but it might be possible if the document's contents were modified outside of RediSearch. Since the document is just a normal hash, we can't really safeguard against it. We can put extra checks into place, though.

**Comment by gkorland** [comment]
@mnunberg why do you think it will crash the server?
